function checkBadTrialsEEG_GAV(dataLog)
    if ~exist('dataLog','var')
        fileExt = {'*.mat'};
        [hdrfile,path] = uigetfile(fileExt, 'Select dataLog file...');
        if hdrfile(1) == 0, return; end
        fname = fullfile(path,hdrfile);
        dataL = load(fname);
        dataLog = dataL.dataLog;
    end
    
    [dataLog,folderName] = getFolderDetails(dataLog);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    fontSizeSmall = 10; fontSizeLarge = 16;
    labelStartX = 0.01; labelStartY = 0.01; labelWidth = 0.49; prepLabelHeight = 0.075;
    backgroundColor = 'w';
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    hPrepPanel = uipanel('Title','Preprocessing','fontSize', fontSizeLarge, ...
    'Unit','Normalized','Position',[0.1 0.18 0.8 0.8]);
    
    uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
        'Position',[labelStartX labelStartY+8*prepLabelHeight labelWidth prepLabelHeight],...
        'Style','text','String','Algorithmically Reject Bad Trials:','FontSize',fontSizeSmall);
    hAlgRejectBT = uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
        'BackgroundColor',backgroundColor,'Position',[labelStartX+labelWidth labelStartY+8*prepLabelHeight labelWidth prepLabelHeight],...
        'Style','popup','String','Yes|No','FontSize',fontSizeSmall);

    uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
            'Position',[labelStartX labelStartY+7*prepLabelHeight labelWidth prepLabelHeight],...
            'Style','text','String','Check Electrodes for Bad Trials:','FontSize',fontSizeSmall);
    hCheckElecsBT = uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
        'BackgroundColor',backgroundColor,'Position',[labelStartX+labelWidth labelStartY+7*prepLabelHeight labelWidth prepLabelHeight],...
        'Style','edit','FontSize',fontSizeSmall);

    uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
            'Position',[labelStartX labelStartY+6*prepLabelHeight labelWidth prepLabelHeight],...
            'Style','text','String','Threshold for Bad Trials:','FontSize',fontSizeSmall);
    hThresholdBT = uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
        'BackgroundColor',backgroundColor,'Position',[labelStartX+labelWidth labelStartY+6*prepLabelHeight labelWidth prepLabelHeight],...
        'Style','edit','String','6','FontSize',fontSizeSmall);
    
    uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
            'Position',[labelStartX labelStartY+5*prepLabelHeight labelWidth prepLabelHeight],...
            'Style','text','String','Min limit for Bad Trials:','FontSize',fontSizeSmall);
    hMinBT = uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
        'BackgroundColor',backgroundColor,'Position',[labelStartX+labelWidth labelStartY+5*prepLabelHeight labelWidth prepLabelHeight],...
        'Style','edit','String','-50','FontSize',fontSizeSmall);
    
    uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
            'Position',[labelStartX labelStartY+4*prepLabelHeight labelWidth prepLabelHeight],...
            'Style','text','String','Max limit for Bad Trials:','FontSize',fontSizeSmall);
    hMaxBT = uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
        'BackgroundColor',backgroundColor,'Position',[labelStartX+labelWidth labelStartY+4*prepLabelHeight labelWidth prepLabelHeight],...
        'Style','edit','String','50','FontSize',fontSizeSmall);

    uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
            'Position',[labelStartX labelStartY+3*prepLabelHeight labelWidth prepLabelHeight],...
            'Style','text','String','Save Bad Trials:','FontSize',fontSizeSmall);
    hSaveBT = uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
        'BackgroundColor',backgroundColor,'Position',[labelStartX+labelWidth labelStartY+3*prepLabelHeight labelWidth prepLabelHeight],...
        'Style','popup','String','Yes|No','FontSize',fontSizeSmall);

    uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
            'Position',[labelStartX labelStartY+2*prepLabelHeight labelWidth prepLabelHeight],...
            'Style','text','String','Show Bad Trials:','FontSize',fontSizeSmall);
    hShowBT = uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
        'BackgroundColor',backgroundColor,'Position',[labelStartX+labelWidth labelStartY+2*prepLabelHeight labelWidth prepLabelHeight],...
        'Style','popup','String','No|Yes','FontSize',fontSizeSmall);
    
%     uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
%         'Position',[labelStartX labelStartY+1*prepLabelHeight labelWidth prepLabelHeight],...
%         'Style','text','String','Visually Reject Bad Trials:','FontSize',fontSizeSmall);
%     hVisRejectBT = uicontrol('Parent',hPrepPanel,'Unit','Normalized', ...
%         'BackgroundColor',backgroundColor,'Position',[labelStartX+labelWidth labelStartY+1*prepLabelHeight labelWidth prepLabelHeight],...
%         'Style','popup','String','Yes|No','FontSize',fontSizeSmall);

    uicontrol('Unit','Normalized', ...
        'Position',[0.1 0.1 0.8 prepLabelHeight],...
        'Style','pushbutton','String','Start','FontSize',fontSizeSmall,'Callback',{@start_Callback});
    
    
    function start_Callback(~,~)
        
        checkTheseElectrodesForBadTrials = str2num(get(hCheckElecsBT,'string'));
        thresholdBadTrials = str2num(get(hThresholdBT,'string'));
        minLim = str2num(get(hMinBT,'string'));
        maxLim = str2num(get(hMaxBT,'string'));
        
        saveBadTrialsFlag = get(hSaveBT,'val'); 
        if saveBadTrialsFlag ~= 1; saveBadTrialsFlag = 0; end;
        showTrialsBadTrials = get(hShowBT,'val')-1;
        [~,badTrials] = findBadTrialsEEG_GAV(dataLog,checkTheseElectrodesForBadTrials,thresholdBadTrials,minLim,maxLim,saveBadTrialsFlag,showTrialsBadTrials);
        dataLog(8,2)={badTrials};
        
        save(fullfile(folderName,'dataLog.mat'), 'dataLog');
        
    end
end